{% set name = "MDAnalysisTests" %}
{% set version = "0.19.2" %}
{% set sha256 = "be4c27a11d3f55a00dfe54149508ea6df2d816bd25f57c2bebb8804abf4e927e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win and py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - mdanalysis =={{ version }}
    - psutil
    - mock
    - pytest
    - hypothesis

test:
  imports:
    - MDAnalysisTests
    - MDAnalysisTests.datafiles

about:
  home: https://github.com/MDAnalysis/mdanalysis
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Tests and test files for MDAnalysis package'

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
